DungNguyen1702/Vietnamese-Food-Restaurant

backend/src/app.module.ts, backend/src/modules/category/category.controller.ts, backend/src/modules/category/category.module.ts, backend/src/modules/category/category.service.ts, backend/src/modules/item/item.service.ts
[task 102](https://phamtin482003.atlassian.net/browse/SCRUM-102?atlOrigin=eyJpIjoiYTRmYzA3MzU0MDI2NGFiNmJlNTg0OGZhZDk0M2IwOGEiLCJwIjoiaiJ9)
=> [BE][Guest, Customer][Food List] API lấy list các category

frontend/src/components/auth/FormRegister.jsx, frontend/src/components/auth/formLogin.jsx, frontend/src/components/layouts/MainLayout.jsx
[Task 22](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-22)
=> Task 22: [FE][Guest][Auth] Register page

backend/src/app.module.ts, backend/src/modules/cart/cart.controller.ts, backend/src/modules/cart/cart.module.ts, backend/src/modules/cart/cart.service.ts
[task 32](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-32)
=> [BE][Guest, Customer][Food list] API tạo cart

backend/src/database/migrations/1728907025934-migration_2.ts, backend/src/database/seeders/review.seeder.ts, backend/src/entities/item.entity.ts, backend/src/entities/review.entity.ts, backend/src/entities/voucher.entity.ts, backend/src/i18n/en/error.json, backend/src/i18n/en/success.json, backend/src/i18n/vi/error.json, backend/src/i18n/vi/success.json, backend/src/main.ts, backend/src/modules/cart/cart.controller.ts, backend/src/modules/cart/cart.service.ts, backend/src/modules/item/item.service.ts, backend/src/modules/order/order.service.ts, backend/src/modules/payment/zaloPayment.controller.ts, backend/src/modules/payment/zaloPayment.service.ts
[task.44](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-44&text=%5BBE%5D)
=> [BE][Customer][Shipping cart] API update, delete cart

backend/.env.example, backend/src/app.module.ts, backend/src/entities/order.entity.ts, backend/src/modules/momo-payment/momo-payment.controller.ts, backend/src/modules/momo-payment/momo-payment.module.ts, backend/src/modules/momo-payment/momo-payment.service.ts, backend/src/modules/order/order.service.ts
[Task.41](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-41)
=> [BE][Customer][Order Item] API thanh toán qua MoMo

backend/.env.example, backend/src/app.module.ts, backend/src/database/seeders/index.ts, backend/src/database/seeders/voucher.seeder.ts, backend/src/i18n/en/validation.json, backend/src/i18n/vi/validation.json, backend/src/modules/order/dtos/orderRequest.ts, backend/src/modules/order/order.service.ts, backend/src/modules/payment/momo-payment.controller.ts, backend/src/modules/payment/momo-payment.service.ts, backend/src/modules/payment/payment.module.ts, backend/src/modules/payment/zalo-payment.controller.ts, backend/src/modules/payment/zalo-payment.service.ts, backend/src/modules/voucher/voucher.controller.ts, backend/src/modules/voucher/voucher.module.ts, backend/src/modules/voucher/voucher.service.ts
[task 103](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-103)
=> [BE][Customer][ShippingCart] API lấy tất cả discount có trong hệ thống

backend/src/app.module.ts, backend/src/i18n/en/error.json, backend/src/i18n/en/validation.json, backend/src/i18n/vi/error.json, backend/src/i18n/vi/validation.json, backend/src/modules/cart/cart.service.ts, backend/src/modules/item/item.service.ts, backend/src/modules/order/order.service.ts, backend/src/modules/payment/zalo-payment.service.ts, backend/src/modules/review/dtos/ReviewRequest.ts, backend/src/modules/review/review.controller.ts, backend/src/modules/review/review.module.ts, backend/src/modules/review/review.service.ts
[task 50](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-50&text=%5BBE%5D)
=> [BE][Customer][Food review] API create review

backend/src/i18n/en/validation.json, backend/src/i18n/vi/validation.json, backend/src/modules/order/dtos/ordersRequest.ts, backend/src/modules/order/order.controller.ts, backend/src/modules/order/order.service.ts, backend/src/modules/voucher/voucher.controller.ts, backend/src/modules/voucher/voucher.service.ts
[task 52](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-52&text=%5BBE%5D)
=> [BE][Customer][Ordered management] API lấy list các order

backend/src/i18n/en/error.json, backend/src/i18n/vi/error.json, backend/src/modules/order/order.controller.ts, backend/src/modules/order/order.service.ts
[task 66](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-66&text=%5BBE%5D)
=> [BE][Staff, Admin][Order management] API lấy tất cả thông tin của order theo OrderID

backend/src/app.module.ts, backend/src/common/utils/item.filter.utils.ts, backend/src/modules/revenue/revenue.controller.ts, backend/src/modules/revenue/revenue.module.ts, backend/src/modules/revenue/revenue.service.ts
[task 62](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-62&text=%5BBE%5D)
=> [BE][Staff, Admin][Revenue statistics] API revenue

backend/.env.example, backend/src/database/migrations/1729676512135-migration_version4.ts, backend/src/database/seeders/drink-size.seeder.ts, backend/src/database/seeders/drink_data.json, backend/src/database/seeders/food-size.seeder.ts, backend/src/database/seeders/food_data.json, backend/src/database/seeders/index.ts, backend/src/database/seeders/like.seeder.ts, backend/src/database/seeders/review.seeder.ts, backend/src/entities/item.entity.ts, backend/src/i18n/en/success.json, backend/src/i18n/vi/success.json, backend/src/modules/cart/cart.service.ts, backend/src/modules/like/like.controller.ts, backend/src/modules/like/like.module.ts, backend/src/modules/like/like.service.ts, backend/src/modules/payment/zalo-payment.service.ts, frontend/.env, frontend/src/views/pages/fooddetail/index.jsx, frontend/src/views/pages/login/index.jsx
[task 46](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-46&text=%5BBE%5D)
=> [BE][Customer][Like food]API update like ( nếu chưa có thì tạo ra còn nếu có rồi thì delete )

backend/src/modules/order/admin.order.controller.ts, backend/src/modules/order/admin.order.service.ts
[task 67](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-67&text=%5BBE%5D)
=> [BE][Staff, Admin][Order management] API update thông tin của order theo OrderID

backend/src/i18n/en/error.json, backend/src/i18n/en/validation.json, backend/src/i18n/vi/error.json, backend/src/i18n/vi/validation.json, backend/src/modules/order/dtos/cusCancelRequest.ts, backend/src/modules/order/order.controller.ts, backend/src/modules/order/order.service.ts
[Task.56](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?assignee=63e9e1932661cde223368592&selectedIssue=SCRUM-56)
=> [BE][Customer][Ordered management] API cancel order

backend/src/modules/account/account.controller.ts, backend/src/modules/account/account.service.ts
[Task.59](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?assignee=63e9e1932661cde223368592&selectedIssue=SCRUM-59)
=> [BE][All][personal Info management] API lấy thông tin của người dùng thông qua token

AI/app.py, backend/src/entities/account.entity.ts, backend/src/i18n/en/error.json, backend/src/i18n/vi/error.json, backend/src/modules/account/account.controller.ts, backend/src/modules/account/account.service.ts, backend/src/modules/account/dtos/accountUpdateDto.ts
[Task.60 ](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?assignee=63e9e1932661cde223368592&selectedIssue=SCRUM-60)
=> [BE][All][personal Info management] API update thông tin của người dùng

backend/src/app.module.ts, backend/src/i18n/en/error.json, backend/src/i18n/vi/error.json, backend/src/modules/admin/voucher/voucher.controller.ts, backend/src/modules/admin/voucher/voucher.module.ts, backend/src/modules/admin/voucher/voucher.service.ts, backend/src/modules/order/order.module.ts, backend/src/modules/order/order.service.ts, backend/src/modules/payment/payment.module.ts, backend/src/modules/review/review.service.ts
[task 89](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-89&text=%5BBE%5D)
=> [BE][Admin][Voucher management] API danh sách các voucher

backend/src/i18n/en/error.json, backend/src/i18n/en/validation.json, backend/src/i18n/vi/error.json, backend/src/i18n/vi/validation.json, backend/src/modules/admin/voucher/dtos/updateVoucher.request.ts, backend/src/modules/admin/voucher/voucher.controller.ts, backend/src/modules/admin/voucher/voucher.service.ts, backend/src/modules/order/order.service.ts
[task 93](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-93&text=%5BBE%5D)
=> [BE][Admin][Voucher management] API update voucher

backend/src/i18n/en/error.json, backend/src/i18n/vi/error.json, backend/src/modules/admin/voucher/dtos/createVoucher.request.ts, backend/src/modules/admin/voucher/voucher.controller.ts, backend/src/modules/admin/voucher/voucher.service.ts
[Task.91](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?assignee=63e9e1932661cde223368592&selectedIssue=SCRUM-91)
=> [BE][Admin][Voucher management] API create voucher

backend/src/modules/admin/account/account.controller.ts, backend/src/modules/admin/account/account.service.ts
[Task.80](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?assignee=63e9e1932661cde223368592&selectedIssue=SCRUM-80)
=> [BE][Staff, Admin][Customer account management] API lấy account detail

frontend/.env, frontend/package-lock.json, frontend/package.json, frontend/src/api/cartAPI.js, frontend/src/api/modelAPI.js, frontend/src/api/orderAPI.js, frontend/src/components/auth/formLogin.jsx, frontend/src/components/detect_modal/UploadModal.jsx, frontend/src/components/detect_modal/constant.js, frontend/src/components/food/ItemCarousel.jsx, frontend/src/components/history/HistoryTable.jsx, frontend/src/components/history/HistoryTable.scss, frontend/src/components/layouts/MainLayout.jsx, frontend/src/components/recommend_modal/RecommendModal.jsx, frontend/src/components/recommend_modal/RecommendModal.scss, frontend/src/components/sidebar/UserSidebar.jsx, frontend/src/components/sidebar/UserSidebar.scss, frontend/src/components/sidebar/constant.js, frontend/src/components/wishlist/WishlistCard.jsx, frontend/src/components/wishlist/WishlistCard.scss, frontend/src/contexts/CartContext.js, frontend/src/views/pages/dashboard/index.jsx, frontend/src/views/pages/dashboard/index.scss, frontend/src/views/pages/wishlist/constant.js, frontend/src/views/pages/wishlist/index.jsx, frontend/src/views/pages/wishlist/index.scss, frontend/src/views/routes/index.js
[Task 57](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog)
=> [FE][Customer][Account Controller management] Dashboard page

backend/src/modules/order/order.service.ts, frontend/.env, frontend/.gitignore, frontend/package-lock.json, frontend/package.json, frontend/src/components/auth/formLogin.jsx, frontend/src/components/headers/index.jsx, frontend/src/components/headers/index.scss, frontend/src/components/layouts/AdminLayout.jsx, frontend/src/components/layouts/AdminLayout.scss, frontend/src/contexts/AccountContext.js, frontend/src/views/pages/admin-dashboard/index.jsx, frontend/src/views/pages/login/index.jsx, frontend/src/views/routes/admin-route.js, frontend/src/views/routes/customer-route.js, frontend/src/views/routes/index.js, frontend/src/views/routes/staff-route.js
[task 105](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-105)
=> [FE][Staff, Admin][Revenune statistics] Tạo admin layout

frontend/src/api/orderAPI.js, frontend/src/components/detect_modal/DetectModal.scss, frontend/src/components/detect_modal/UploadModal.jsx, frontend/src/components/detect_modal/constant.js, frontend/src/components/food/ItemCarousel.jsx, frontend/src/components/history/OrderTable.jsx, frontend/src/components/history/RatingModal.jsx, frontend/src/components/history/RatingModal.scss, frontend/src/components/wishlist/WishlistCard.jsx, frontend/src/constants/enum.js, frontend/src/views/pages/historyDetail/index.jsx, frontend/src/views/pages/wishlist/constant.js, frontend/src/views/routes/index.js
[Task 49](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-49)
=> [FE][Customer][Ordered management] Order detail page

frontend/src/api/orderAPI.js, frontend/src/components/history/CancelModal.jsx, frontend/src/components/history/CancelModal.scss, frontend/src/views/pages/historyDetail/index.jsx
[Task 55](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-55)
=> [FE][Customer][Ordered management] Cancel reason modal

backend/src/entities/item-size.entity.ts, backend/src/modules/admin/account/account.service.ts, backend/src/modules/admin/account/dtos/updateAccount.request.ts, backend/src/modules/admin/item/dtos/updateItem.request.ts, backend/src/modules/admin/item/item.service.ts, frontend/src/api/accountAPI.js, frontend/src/constants/colors.scss, frontend/src/constants/enum.js, frontend/src/utils/string.js, frontend/src/views/pages/admin-accounts/components/account-create/index.jsx, frontend/src/views/pages/admin-accounts/components/account-detail/index.jsx, frontend/src/views/pages/admin-accounts/components/account-detail/index.scss, frontend/src/views/pages/admin-accounts/components/account-update/index.jsx, frontend/src/views/pages/admin-accounts/index.jsx, frontend/src/views/pages/admin-accounts/index.scss
[task 78](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJwIjoiaiIsImkiOiIxMjkzYzhkMzYzNDc0ODYyOWFjYWIxMzk4YjMwNzBlNiJ9&cloudId=9ef2b301-dd4f-4cd6-bba6-bf8049df5e70&selectedIssue=SCRUM-78)
=> [FE][Staff, Admin][Customer account management] Customer account detaill page

frontend/src/api/accountAPI.js, frontend/src/components/headers/index.jsx, frontend/src/components/input/PasswordInput.jsx, frontend/src/components/sidebar/UserSidebar.jsx, frontend/src/components/sidebar/constant.js, frontend/src/contexts/AccountContext.js, frontend/src/views/pages/account-detail/index.jsx, frontend/src/views/pages/account-detail/index.scss, frontend/src/views/routes/index.js
[Task 58](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-58)
=> [FE][All][personal Info management] Personal info management page

frontend/src/api/accountAPI.js, frontend/src/components/auth/FormRegister.jsx, frontend/src/components/headers/index.jsx, frontend/src/components/input/PasswordInput.jsx, frontend/src/utils/axiosCustomize.js, frontend/src/views/pages/admin-accounts/components/account-create/index.jsx, frontend/src/views/pages/admin-accounts/index.jsx
[Task 85](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-85)
=> [FE][Admin][Staff account management] Create Staff account page

backend/src/modules/auth/auth.controller.ts, backend/src/modules/auth/auth.service.ts, backend/src/modules/mailer/mailer.service.ts, frontend/src/api/LoginAPI.js, frontend/src/api/accountAPI.js, frontend/src/components/auth/FormRegister.jsx, frontend/src/components/auth/formLogin.jsx, frontend/src/views/pages/account-detail/index.jsx, frontend/src/views/pages/reset-password/index.jsx, frontend/src/views/pages/reset-password/index.scss, frontend/src/views/routes/index.js
[Task 24](https://phamtin482003.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?selectedIssue=SCRUM-24)
=> [FE][Guest][Auth] Forgot password page
